export const NAV_LINKS = ["Collections", "About", "Stores", "Journal"];

export const PRODUCTS = [
  {
    id: 1,
    name: "Nuit Dorée",
    house: "Maison Éclat",
    note: "Oud · Amber · Sandalwood",
    price: 4800,
    tag: "Bestseller",
    aspect: "tall",
    category: "Oriental",
    gender: "Unisex",
    year: 2020,
    country: "France",
    description:
      "Nuit Dorée opens with a smoky whisper of oud before revealing its warm amber heart. The base settles into a creamy sandalwood — rich, lingering, and deeply intimate. Ideal for evenings and cooler months.",
    topNotes: ["Saffron", "Black Pepper", "Cardamom"],
    heartNotes: ["Oud", "Rose Absolute", "Amber"],
    baseNotes: ["Sandalwood", "Musk", "Vanilla"],
    sizes: ["50ml", "100ml"],
    stock: 12,
    rating: 4.8,
    reviews: 34,
  },
  {
    id: 2,
    name: "Blanc de Soie",
    house: "Atelier Lumière",
    note: "White Musk · Iris · Vetiver",
    price: 3600,
    tag: "New Arrival",
    aspect: "wide",
    category: "Floral",
    gender: "Feminine",
    year: 2023,
    country: "France",
    description:
      "A silken veil of white musk wrapped around cool iris petals and earthy vetiver. Blanc de Soie is understated luxury — the kind of scent noticed only when you leave the room.",
    topNotes: ["Aldehydes", "Bergamot", "Pink Pepper"],
    heartNotes: ["Iris", "White Rose", "Peony"],
    baseNotes: ["White Musk", "Vetiver", "Ambrette"],
    sizes: ["30ml", "50ml", "100ml"],
    stock: 8,
    rating: 4.6,
    reviews: 19,
  },
  {
    id: 3,
    name: "Opéra Rouge",
    house: "La Galerie Olfactive",
    note: "Rose · Patchouli · Cedarwood",
    price: 5200,
    tag: "Exclusive",
    aspect: "square",
    category: "Floral",
    gender: "Feminine",
    year: 2019,
    country: "Belgium",
    description:
      "Named after the grandeur of the opera house, this fragrance commands attention. A theatrical rose anchored by dark patchouli and warm cedarwood — dramatic, sensual, unforgettable.",
    topNotes: ["Raspberry", "Grapefruit", "Elemi"],
    heartNotes: ["Turkish Rose", "Geranium", "Patchouli"],
    baseNotes: ["Cedarwood", "Labdanum", "Benzoin"],
    sizes: ["50ml", "100ml"],
    stock: 5,
    rating: 4.9,
    reviews: 52,
  },
  {
    id: 4,
    name: "Sel de Mer",
    house: "Côte Studio",
    note: "Sea Salt · Driftwood · Bergamot",
    price: 3100,
    tag: null,
    aspect: "square",
    category: "Fresh",
    gender: "Unisex",
    year: 2022,
    country: "Portugal",
    description:
      "Bottled ocean air. Sel de Mer captures the first breath of sea breeze at dawn — briny salt, bleached driftwood, and the citrus brightness of bergamot. Light, effortless, alive.",
    topNotes: ["Bergamot", "Sea Salt", "Marine Accord"],
    heartNotes: ["Driftwood", "Vetiver", "Galbanum"],
    baseNotes: ["White Musk", "Ambergris", "Cedarwood"],
    sizes: ["50ml", "100ml", "150ml"],
    stock: 20,
    rating: 4.5,
    reviews: 28,
  },
  {
    id: 5,
    name: "Forêt Noire",
    house: "Sylvain Parfums",
    note: "Pine · Moss · Dark Amber",
    price: 4200,
    tag: "Staff Pick",
    aspect: "square",
    category: "Woody",
    gender: "Masculine",
    year: 2021,
    country: "Germany",
    description:
      "A walk through a rain-soaked pine forest at dusk. Forêt Noire layers resinous pine over damp oakmoss and a base of dark amber — primal, grounding, and deeply masculine.",
    topNotes: ["Pine Needle", "Juniper", "Eucalyptus"],
    heartNotes: ["Oakmoss", "Fir Balsam", "Violet Leaf"],
    baseNotes: ["Dark Amber", "Benzoin", "Patchouli"],
    sizes: ["50ml", "100ml"],
    stock: 14,
    rating: 4.7,
    reviews: 41,
  },
  {
    id: 6,
    name: "Velours Sucré",
    house: "Pâtisserie Olfactive",
    note: "Tonka · Praline · Heliotrope",
    price: 3800,
    tag: null,
    aspect: "square",
    category: "Gourmand",
    gender: "Feminine",
    year: 2022,
    country: "France",
    description:
      "An ode to the Parisian pâtisserie. Velours Sucré blends warm tonka bean with nutty praline and powdery heliotrope — sweet without being cloying, comforting without being simple.",
    topNotes: ["Heliotrope", "Almond", "Bergamot"],
    heartNotes: ["Praline", "Jasmine", "Vanilla Orchid"],
    baseNotes: ["Tonka Bean", "Sandalwood", "White Musk"],
    sizes: ["30ml", "50ml"],
    stock: 9,
    rating: 4.4,
    reviews: 22,
  },
  {
    id: 7,
    name: "Soleil Citrus",
    house: "Côte Studio",
    note: "Yuzu · Neroli · Ginger",
    price: 2900,
    tag: "New Arrival",
    aspect: "square",
    category: "Citrus",
    gender: "Unisex",
    year: 2024,
    country: "Spain",
    description:
      "Pure Mediterranean sunshine. Soleil Citrus sparks with Japanese yuzu and French neroli over a gingered dry-down — effortlessly bright, endlessly wearable.",
    topNotes: ["Yuzu", "Lemon Verbena", "Grapefruit"],
    heartNotes: ["Neroli", "Ginger", "White Tea"],
    baseNotes: ["Cedarwood", "Musk", "Vetiver"],
    sizes: ["50ml", "100ml", "150ml"],
    stock: 25,
    rating: 4.3,
    reviews: 11,
  },
  {
    id: 8,
    name: "Herbe Folle",
    house: "Atelier Lumière",
    note: "Lavender · Coumarin · Oakmoss",
    price: 3400,
    tag: null,
    aspect: "square",
    category: "Woody",
    gender: "Masculine",
    year: 2020,
    country: "France",
    description:
      "The classic fougère reimagined. Fresh lavender fades into a coumarin-rich heart before oakmoss and tonka anchor it with timeless elegance. The gentleman's signature.",
    topNotes: ["Lavender", "Bergamot", "Lemon"],
    heartNotes: ["Coumarin", "Geranium", "Clary Sage"],
    baseNotes: ["Oakmoss", "Tonka Bean", "Vetiver"],
    sizes: ["50ml", "100ml"],
    stock: 16,
    rating: 4.6,
    reviews: 37,
  },
];

// Homepage featured — first 4 items, price formatted
export const FEATURED = PRODUCTS.slice(0, 4).map((p) => ({
  ...p,
  priceRaw: p.price,
  price: `₱${p.price.toLocaleString()}`,
}));

export const CATEGORIES = ["All", "Floral", "Oriental", "Fresh", "Woody", "Gourmand", "Citrus"];

export const MARQUEE_ITEMS = [
  "Niche Fragrances",
  "Free Shipping ₱2,000+",
  "Authentic Imports",
  "Gift Wrapping Available",
  "New Arrivals Weekly",
  "100% Authentic",
];

export const WHY_US = [
  {
    num: "01",
    title: "100% Authentic",
    body: "Every fragrance is sourced directly from European houses or authorised distributors.",
  },
  {
    num: "02",
    title: "Expert Curation",
    body: "Our team of fragrance connoisseurs selects only the most distinctive and high-quality scents.",
  },
  {
    num: "03",
    title: "Nationwide Delivery",
    body: "Fast and secure shipping across the Philippines, with gift wrapping on request.",
  },
];

export const FOOTER_LINKS = ["Privacy", "Terms", "Shipping", "Returns", "Contact"];